export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGOUT = "USER_LOGOUT";

export const BUGS_LIST_SUCCESS = "BUGS_LIST_SUCCESS";
export const BUGS_LIST_FAIL = "BUGS_LIST_FAIL";
export const BUG_DETAILS_REQUEST = "BUG_DETAILS_REQUEST";
export const BUG_DETAILS_SUCCESS = "BUG_DETAILS_SUCCESS";
export const BUG_DETAILS_FAIL = "BUG_DETAILS_FAIL";
export const BUG_DELETE_REQUEST = "BUG_DELETE_REQUEST";
export const BUG_DELETE_SUCCESS = "BUG_DELETE_SUCCESS";
export const BUG_DELETE_FAIL = "BUG_DELETE_FAIL";
export const BUG_CREATE_REQUEST = "BUG_CREATE_REQUEST";
export const BUG_CREATE_SUCCESS = "BUG_CREATE_SUCCESS";
export const BUG_CREATE_FAIL = "BUG_CREATE_FAIL";
export const BUG_UPDATE_REQUEST = "BUG_UPDATE_REQUEST";
export const BUG_UPDATE_SUCCESS = "BUG_UPDATE_SUCCESS";
export const BUG_UPDATE_FAIL = "BUG_UPDATE_FAIL";
export const BUG_UPDATE_RESET = "BUG_UPDATE_RESET";
